# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 33) do

  create_table "acceptance_criteria", :force => true do |t|
    t.column "detail",        :string
    t.column "user_story_id", :integer
  end

  create_table "accounts", :force => true do |t|
    t.column "name",              :string
    t.column "time_zone",         :string
    t.column "account_holder_id", :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "iteration_length",  :integer
  end

  create_table "burndowns", :force => true do |t|
    t.column "sprint_id",  :integer
    t.column "hours_left", :integer
    t.column "created_on", :date
  end

  add_index "burndowns", ["sprint_id", "created_on"], :name => "index_burndowns_on_sprint_id_and_created_on"
  add_index "burndowns", ["sprint_id"], :name => "index_burndowns_on_sprint_id"

  create_table "people", :force => true do |t|
    t.column "name",            :string
    t.column "email",           :string
    t.column "account_id",      :integer
    t.column "password",        :string
    t.column "authenticated",   :integer,  :limit => 2, :default => 0
    t.column "activation_code", :string
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "type",            :string
  end

  create_table "project_members", :force => true do |t|
    t.column "person_id",  :integer
    t.column "project_id", :integer
  end

  create_table "projects", :force => true do |t|
    t.column "name",             :string
    t.column "iteration_length", :string
    t.column "work_hours",       :string
    t.column "account_id",       :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "releases", :force => true do |t|
    t.column "name",       :string
    t.column "end_date",   :datetime
    t.column "account_id", :integer
  end

  add_index "releases", ["name", "account_id"], :name => "index_releases_on_name_and_account_id", :unique => true

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "sprint_elements", :force => true do |t|
    t.column "sprint_id",     :integer
    t.column "user_story_id", :integer
    t.column "position",      :integer
  end

  create_table "sprints", :force => true do |t|
    t.column "account_id", :integer
    t.column "start_at",   :datetime
    t.column "end_at",     :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "goal",       :text
    t.column "name",       :string
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer,                 :null => false
    t.column "taggable_id",   :integer,                 :null => false
    t.column "taggable_type", :string,  :default => "", :null => false
  end

  add_index "taggings", ["tag_id", "taggable_id", "taggable_type"], :name => "index_taggings_on_tag_id_and_taggable_id_and_taggable_type", :unique => true

  create_table "tags", :force => true do |t|
    t.column "name",       :string,  :default => "", :null => false
    t.column "account_id", :integer
  end

  add_index "tags", ["name", "account_id"], :name => "index_tags_on_name_and_account_id", :unique => true

  create_table "tasks", :force => true do |t|
    t.column "definition",    :string
    t.column "description",   :string
    t.column "hours",         :integer
    t.column "position",      :integer
    t.column "developer_id",  :integer
    t.column "user_story_id", :integer
  end

  create_table "themes", :force => true do |t|
    t.column "name",        :string,  :default => "", :null => false
    t.column "account_id",  :integer
    t.column "description", :text
  end

  add_index "themes", ["name", "account_id"], :name => "index_themes_on_name_and_account_id", :unique => true

  create_table "themings", :force => true do |t|
    t.column "theme_id",      :integer,                 :null => false
    t.column "themable_id",   :integer,                 :null => false
    t.column "themable_type", :string,  :default => "", :null => false
  end

  add_index "themings", ["theme_id", "themable_id", "themable_type"], :name => "index_themings_on_theme_id_and_themable_id_and_themable_type", :unique => true

  create_table "user_stories", :force => true do |t|
    t.column "definition",   :text
    t.column "description",  :text
    t.column "story_points", :integer
    t.column "position",     :integer
    t.column "done",         :integer,  :limit => 2, :default => 0, :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "sprint_id",    :integer
    t.column "account_id",   :integer
    t.column "release_id",   :integer
  end

end
